data:
  type: nerf_synthesic
  half_size: False
  batch_size: 1
  near: 2.0
  far: 6.0

sampler:
  importance: False
  near: 2.0
  far: 6.0
  num_sample: 64
  num_importance: 128

hash_grid_enc:
  L: 16
  log2T: 19
  F: 2
  N_min: 16
  N_max: 512

dir_freq_enc:
  L: 2

pos_freq_enc:
  L: 5

sh_enc:
  input_dim: 3
  degree: 4

decoder: 'NeRF'

decoder1:
  pos_dim: 32
  view_dim: 16

  sigma_net:
    num_layers: 2
    hidden_dim: 64
    out_dim: 16

  color_net:
    num_layers: 3
    hidden_dim: 64
    out_dim: 3

decoder2:
  pos_dim: 63
  view_dim: 27

  sigma_net:
    num_layers: 8
    hidden_dim: 256

renderer:

trainer:
  optim:
  sched:

loss:

epoches: 1000

tensorboard_path: log/
checkpoints_path: ckpt/

valid_iter: 999
save_iter: 9999