data:
  type: nerf_synthesic
  batch_size: 2
  near: 2.0
  far: 6.0

sampler:
  near: 2.0
  far: 6.0
  num_sample: 64

hash_grid_enc:
  L: 16
  log2T: 19
  F: 2
  N_min: 16
  N_max: 512

freq_enc:
  L: 3

sh_enc:
  input_dim: 3
  degree: 4

decoder:
  pos_dim: 32
  view_dim: 16

  sigma_net:
    num_layers: 2
    hidden_dim: 64
    out_dim: 16

  color_net:
    num_layers: 3
    hidden_dim: 64
    out_dim: 3

renderer:

trainer:
  optim:
  sched:

loss:

epoches: 5000

tensorboard_path: log/
checkpoints_path: ckpt/

valid_iter: 100
save_iter: 1000