data:
  type: nerf_synthesic

encoder:
  arch: hash_grid

  hash_grid:
    L: 16
    log2T: 19
    F: 2
    N_min: 16
    N_max: 512

decoder:
  arch: simple_nerf

  nerf:
    sigma_net:

    color_net:

  simple_nerf:
    sigma_net:
      num_layers: 2
      hidden_dim: 64
      out_dim: 16
    color_net:
      num_layers: 3
      hidden_dim: 64
      out_dim: 3

trainer:

loss: